name: Build firmware

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: martinfger/iot_devel:1.0

    steps:
#      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          cd /home/esp
          rm -rf esp_wifi_repeater
          git clone https://github.com/shafr/esp_wifi_repeater.git
          cd esp_wifi_repeater
          make 
          tar cf firmware.tar firmware/
          gzip firmware.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.CURR_DATE }}-firmware.tar.gz
          path: /home/esp/esp_wifi_repeater/firmware.tar.gz
